


# FROM eclipse-temurin:25-jre
# #pas toucher sa


# COPY  target/*.jar app.jar

# ENTRYPOINT ["java", "-jar", "app.jar"]







FROM eclipse-temurin:25-jre





ENTRYPOINT ["java","-jar","app.jar"]