spring.application.name=Scanner-Service

# Server
server.port=8080
eureka.client.enables=false
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.blqictiayspmcyrjtqsq
spring.datasource.password=StockageMOH2005
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=scanner_service
spring.datasource.hikari.maximum-pool-size=10

#http://localhost:8081/swagger
springdoc.swagger-ui.path=/swagger
#http://localhost:8081/api-docs
springdoc.api-docs.path=/api-docs


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Actuator
management.endpoints.web.exposure.include=health,info,beans
management.endpoint.health.show-details=always
server.forward-headers-strategy=framework


#confij
spring.cloud.config.enabled=false
# Eureka

EUREKA_CLIENT_ENABLED=false
eureka.instance.prefer-ip-address=true